[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
build_flags =
	-D USBCON
	-D HAL_PCD_MODULE_ENABLED
lib_deps =
	levi--g/USBLibrarySTM32
	arduino-libraries/Keyboard@^1.0.6


upload_command = openocd -f interface/cmsis-dap.cfg -f target/stm32f4x.cfg -c "program .pio/build/blackpill_f411ce/firmware.elf verify reset exit"
# upload_protocol = dfu